"""add call_logs and call_messages tables

Revision ID: f059c349801a
Revises: 04f466c7e8e6
Create Date: 2026-03-11 22:12:13.855020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f059c349801a'
down_revision: Union[str, Sequence[str], None] = '04f466c7e8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_sid', sa.String(length=64), nullable=False),
    sa.Column('caller_phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_call_sid'), 'call_logs', ['call_sid'], unique=True)
    op.create_table('call_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_log_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_args', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_messages_call_log_id'), 'call_messages', ['call_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_messages_call_log_id'), table_name='call_messages')
    op.drop_table('call_messages')
    op.drop_index(op.f('ix_call_logs_call_sid'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
